<script setup lang="ts">
import type { InterviewQuestionFeedback } from '../../api/client'
defineProps<{ feedback: InterviewQuestionFeedback }>()
const noteLabels: Record<string, string> = { ERROR: '回答错误', INCORRECT: '回答错误', INSUFFICIENT_EVIDENCE: '依据不足', MISSING_EVIDENCE: '依据不足', MISSING: '尚未提供', SUPPORTED: '已有依据', STRENGTH: '已有依据' }
</script>
<template><section class="feedback-panel"><header><strong>本题评价 · {{ feedback.score ?? '—' }} 分</strong><el-tag :type="feedback.mocked ? 'warning' : 'success'">{{ feedback.mocked ? '演示评价' : '逐题评价' }}</el-tag></header><p v-if="feedback.summary" class="feedback-summary">{{ feedback.summary }}</p><p v-if="feedback.suggestions?.length" class="primary-suggestion">{{ feedback.suggestions[0] }}</p><details v-if="feedback.dimensions?.length || feedback.evidence?.length || (feedback.suggestions?.length || 0) > 1 || feedback.rubricVersion || feedback.analysisMetadata?.model" class="feedback-details"><summary>完整评价与依据</summary><div v-if="feedback.dimensions?.length" class="dimensions"><article v-for="dimension in feedback.dimensions" :key="dimension.dimension"><strong>{{ dimension.label }} · {{ dimension.score }} 分</strong><p>{{ dimension.explanation }}</p></article></div><div v-if="feedback.evidence?.length" class="evidence-list"><blockquote v-for="(note, index) in feedback.evidence" :key="index"><b>{{ noteLabels[note.type] || note.type }}</b><p v-if="note.quote">“{{ note.quote }}”</p><p>{{ note.finding }}</p></blockquote></div><ul v-if="(feedback.suggestions?.length || 0) > 1" class="additional-suggestions"><li v-for="item in feedback.suggestions?.slice(1)" :key="item">{{ item }}</li></ul><small v-if="feedback.rubricVersion">评价标准 {{ feedback.rubricVersion }} · {{ feedback.analysisMetadata?.model || '未记录模型' }}</small></details></section></template>
<style scoped>
.feedback-panel{display:grid;gap:10px;margin:12px 0;padding:0;background:transparent;font-size:13px;min-width:0}.feedback-panel header{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}.feedback-summary,.primary-suggestion{margin:0}.primary-suggestion{padding-left:10px;border-left:3px solid #8db7a2}.feedback-details{border-top:1px solid #dbe8df;padding-top:8px}.feedback-details summary{cursor:pointer;color:#466756;line-height:1.8}.feedback-details .dimensions{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:10px;margin-top:10px}.dimensions article{border-bottom:1px solid #e5ebe7;padding:10px 0;min-width:0}.feedback-panel p{color:#66716c;line-height:1.7;white-space:pre-wrap;overflow-wrap:anywhere}.feedback-panel blockquote{border-left:3px solid #8db7a2;margin:10px 0;padding-left:12px}.feedback-panel ul{padding-left:20px;margin:10px 0 0;line-height:1.9;overflow-wrap:anywhere}.feedback-panel small{color:#66716c;overflow-wrap:anywhere}.feedback-panel details p{margin:4px 0}.evidence-list{margin-top:4px}.feedback-panel .additional-suggestions{margin-top:4px}@media(max-width:560px){.feedback-details .dimensions{grid-template-columns:1fr}}
</style>
